CREATE TABLE [dbo].[FLWSUBPNSINGSYNCVARVALUE] (
    [VALUE]    NVARCHAR (100) NULL,
    [PNIDX]    DECIMAL (10)   NULL,
    [FILETYPE] INT            NULL,
    [VARNAME]  NVARCHAR (100) NULL,
    [SUBPN]    NVARCHAR (30)  NULL
);

