CREATE TABLE [dbo].[FLWSUBPNPROC] (
    [PNIDX]   DECIMAL (18)    NULL,
    [SUBPN]   NVARCHAR (50)   NULL,
    [SEQ]     DECIMAL (18, 3) NULL,
    [PRICODE] NVARCHAR (50)   NULL,
    [SUBCODE] NVARCHAR (50)   NULL,
    [DUPTIME] DECIMAL (18)    NULL,
    [CNAME]   NVARCHAR (200)  NULL,
    [FLOWDIR] NVARCHAR (200)  NULL
);

