CREATE TABLE [dbo].[STKSUBPNMAT] (
    [PNIDX]      DECIMAL (10)    NULL,
    [SUBPN]      NVARCHAR (30)   NULL,
    [STKSEQ]     DECIMAL (10)    NULL,
    [THICK]      DECIMAL (18, 6) NULL,
    [FINALTHICK] DECIMAL (18, 6) NULL,
    [MATTYPE]    NVARCHAR (20)   NULL,
    [NAME]       NVARCHAR (20)   NULL,
    [SUPPLIER]   NVARCHAR (60)   NULL
);

